### ISSUE TITLE
Q: printer protocol

### ISSUE THREAD

**Issue by kossnikita** [AndBondStyle/niimprint#13]
Just question.

Do you have any information about communication protocol or you just analyse serial interface? Is this protocol similar to other printers?

I am developing a project related to this printer and your project helped me a lot in implementing the protocol. Thank you.

**Comment by AndBondStyle** [comment]
@kossnikita as far as I know, there's no "official" information about the protocol, so we're just reverse engineering it bit-by-bit (no pun intended) using a lot of wireshark (usb/bluetooth) captures. Not sure if this protocol is similar to other printers.
