### ISSUE TITLE
Installed niimprint not finding module

### ISSUE THREAD

**Issue by Clam58** [AndBondStyle/niimprint#15]
I followed your install instructions (using poetry etc), but when I try to run I get the following error:

python3 niimprint --help
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/parallels/niimprint/niimprint/__main__.py", line 7, in <module>
    from niimprint import BluetoothTransport, PrinterClient, SerialTransport
ModuleNotFoundError: No module named 'niimprint'

Probably a rookie error but I can't seem to sort it - any help you can offer would be appreciated.

Thanks

**Comment by AndBondStyle** [comment]
If you're using poetry, just use `poetry run python niimprint --help`

**Comment by Clam58** [comment]
Thanks, yes that does work!
