### ISSUE TITLE
Question: Does it connect to server or is it all local?

### ISSUE THREAD

**Issue by The-Young-Maker** [AndBondStyle/niimprint#22]
Hi, I heard that these Niimbot printers were connected to a chineese server when printing from their app (to restrict access and all that sh*t). Is it still true when using this project or is it all local?

**Comment by TheZoc** [comment]
From what I saw from their original Windows application, there is indeed a URL for a couple of REST servers, and they might use it to print.

If you decide to use this python project (or one of its forks), everything is done local through RS232

**Comment by The-Young-Maker** [comment]
Thanks for the info!
