### ISSUE TITLE
Remove left and bottom Margin for Niimbot B1

### ISSUE THREAD

**Issue by TurboLuke** [AndBondStyle/niimprint#25]
During some testing for the B1, I ran into the problem of having left and bottom margin in my resulting print (see the image below, the size of the PNG is set to 370px x 230px). Any ideas how I can get rid of it? Thanks in advance!

![tempImageH80FKc](https://github.com/AndBondStyle/niimprint/assets/38109506/dc440acd-9cdf-4797-9143-a6270bfafa3c)

**Comment by AndBondStyle** [comment]
@TurboLuke I think the image should be 384px wide. I have a B21, and alignment isn't always perfect, especially when you load a new paper roll and print the first label. Maybe try printing two labels in a row, at least it should fix the bottom margin
